#!/bin/bash

# Author: Conner McDaniel
# https://github.com/connermcd/bin
# MIT license

set -e

result=
i=
while [[ $i < 10 && "$result" != *"author = "* ]]; do
    result=$(curl -s "http://api.crossref.org/works/$1/transform/application/x-bibtex")
    i=$(( $i + 1 ))
done
echo "$result"
